apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: namespaced-controller-role
rules:
  - apiGroups:
      - xlineoperator.xline.cloud
    resources:
      - xlineclusters
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - "*"
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespaced-controller-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: namespaced-controller-role
subjects:
  - kind: ServiceAccount
    name: controller-manager
    namespace: system
