[package]
name = "xline-sidecar"
version = "0.1.0"
edition = "2021"
authors = ["DatenLord <dev@datenlord.io>"]
description = "The xline sidecar component of xline-operator"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/xline-kv/xline-operator/tree/main/sidecar"
categories = ["operator"]
keywords = ["kubernetes", "xline", "operator"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.4", features = ["derive"] }
serde_json = "1.0.97"
tera = { version = "1.17.1", default-features = false }
thiserror = "1.0.40"
tokio = { version = "1.0", features = [
    "rt-multi-thread",
    "time",
    "macros",
    "net",
    "signal",
    "sync",
] }
toml = "0.7.4"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
