---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - xline.kvstore.datenlord.com
  resources:
  - xlineclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - xline.kvstore.datenlord.com
  resources:
  - xlineclusters/finalizers
  verbs:
  - update
- apiGroups:
  - xline.kvstore.datenlord.com
  resources:
  - xlineclusters/status
  verbs:
  - get
  - patch
  - update
