# permissions for end users to edit xlineclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: xlinecluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: xline-operator
    app.kubernetes.io/part-of: xline-operator
    app.kubernetes.io/managed-by: kustomize
  name: xlinecluster-editor-role
rules:
- apiGroups:
  - xline.kvstore.datenlord.com
  resources:
  - xlineclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - xline.kvstore.datenlord.com
  resources:
  - xlineclusters/status
  verbs:
  - get
