# permissions for end users to view xlineclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: xlinecluster-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: xline-operator
    app.kubernetes.io/part-of: xline-operator
    app.kubernetes.io/managed-by: kustomize
  name: xlinecluster-viewer-role
rules:
- apiGroups:
  - xline.kvstore.datenlord.com
  resources:
  - xlineclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - xline.kvstore.datenlord.com
  resources:
  - xlineclusters/status
  verbs:
  - get
