apiVersion: xlineoperator.xline.cloud/v1alpha
kind: XlineCluster
metadata:
  name: affinity-xline-cluster
spec:
  size: 3
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - affinity-xline-cluster # This label is internally set and could be used to select pods.
          topologyKey: "kubernetes.io/hostname"
  container:
    image: "datenlord/xline"
    name: "my-xline"
    ports:
      - containerPort: 2379
        name: xline  # This name signifies the port that xline server is listening on.
