apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xline-operator-role
rules:
  - apiGroups:
      - xlineoperator.xline.cloud
    resources:
      - xlineclusters
    verbs:
      - "*"
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - "*"
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - "*"
