apiVersion: xlineoperator.xline.cloud/v1alpha
kind: XlineCluster
metadata:
  name: my-xline-cluster
spec:
  size: 3
  container:
    image: "datenlord/xline"
    name: "my-xline"
    ports:
      - containerPort: 2379
        name: xline  # This name signifies the port that xline server is listening on.
    env:
      - name: RUST_LOG
        value: DEBUG
