name: Merge Image

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

env:
  REPOSITORY: datenlord

jobs:
  merge_image:
    runs-on: ubuntu-latest
    name: Merge Docker Image
    strategy:
      fail-fast: false
      matrix:
        package:
          - xline-operator
    steps:
      - name: Download Digests
        uses: actions/download-artifact@v3
        with:
          name: digests-${{ matrix.package }}
          path: /tmp/digests

      - name: Download Versions
        uses: actions/download-artifact@v3
        with:
          name: versions-${{ matrix.package }}
          path: /tmp/versions

      - name: Export Digests
        working-directory: /tmp/digests
        run: |
          echo digests=$(printf '${{ env.REPOSITORY }}/${{ matrix.package }}@sha256:%s ' *) >> $GITHUB_ENV

      - name: Export Tags
        working-directory: /tmp/versions
        run: |
          echo tags=$(printf -- '-t ${{ env.REPOSITORY }}/${{ matrix.package }}:%s ' *) >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Manifest
        run: |
          docker buildx imagetools create \
                      -t ${{ env.REPOSITORY }}/${{ matrix.package }}:latest \
                      ${{ env.tags }} \
                      ${{ env.digests }}

      - name: Inspect Manifest
        run: |
          docker buildx imagetools inspect ${{ env.REPOSITORY }}/${{ matrix.package }}:latest
