name: Merge Image

on:
  workflow_call: { }

env:
  REPOSITORY: xline-kv

jobs:
  merge_image:
    runs-on: ubuntu-latest
    name: Merge Docker Image
    strategy:
      fail-fast: false
      matrix:
        package:
          - xline-operator
    steps:
      - name: Download Digests
        uses: actions/download-artifact@v3
        with:
          name: digests-${{ matrix.package }}
          path: /tmp/digests

      - name: Download Versions
        uses: actions/download-artifact@v3
        with:
          name: versions-${{ matrix.package }}
          path: /tmp/versions

      - name: Set up Image ID
        run: |
          IMAGE_ID=ghcr.io/${{ env.REPOSITORY }}/${{ matrix.package }}
          echo IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]') >> $GITHUB_ENV

      - name: Export Digests
        working-directory: /tmp/digests
        run: |
          echo digests=$(printf '${{ env.IMAGE_ID }}@sha256:%s ' *) >> $GITHUB_ENV

      - name: Export Tags
        working-directory: /tmp/versions
        run: |
          echo tags=$(printf -- '-t ${{ env.IMAGE_ID }}:%s ' *) >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.REPOSITORY }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Manifest
        run: |
          docker buildx imagetools create \
                      -t ${{ env.IMAGE_ID }}:latest \
                      ${{ env.tags }} \
                      ${{ env.digests }}

      - name: Inspect Manifest
        run: |
          docker buildx imagetools inspect ${{ env.IMAGE_ID }}:latest
