name: Release

on:
  push:
    tags:
      - "v*"

env:
  CI_RUST_TOOLCHAIN: 1.70.0
  REPOSITORY: datenlord

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  publish_image:
    name: Publish Image
    uses: ./.github/workflows/docker.yml
    secrets: inherit
